---
- hosts: all
  gather_facts: false

  tasks:
  - debug: msg="Restarted smbd service"


  -  name: Stop sv smbd, if running
     runit:
       name: smbd
       state: restarted
  
  - name: Run using a project directory
    docker_compose:
         project_src: /home/alex/docker-mysql-master
         state: absent
 
  - name: run the service defined in docker-mysql-master's docker-compose.yml
    docker_compose:
     project_src: /home/alex/docker-mysql-master

