---
- hosts: file
  tasks:
  - name: Wait 300 seconds for port smb of any IP to close active connections, don't start checking for 10 seconds
    wait_for:
     host: 172.16.0.14
     port: 139
     timeout: 5
    register: smbd_port_check
    ignore_errors: yes
  - fail:
      msg: 'Samba port is open'
    when: not smbd_port_check.failed

  - name: Samba demon d'not started
    runit:
     name: smbd
     state: restarted
    when:  smbd_port_check.failed == true

  
  - name: Run using a project directory
    docker_compose:
     project_src: /home/alex/docker-mysql-master
     state: absent
    when:  smbd_port_check.failed == true
 
  - name: run the service defined in docker-mysql-master's docker-compose.yml
    docker_compose:
      project_src: /home/alex/docker-mysql-master
    when:  smbd_port_check.failed == true
 
- hosts: mysql
  tasks: 
  - name: Restarted too Server mysql 
    include: mysql2.yaml

- hosts: zabbix
  tasks:
  - name: Restarted Zabbix Server
    include: zabbix.yaml

