---

- name: Install packages using apt
  apt:
    name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        - python3-pip
        - python3-setuptools
        - virtualenv
        - python-pip 
    state: present
    update_cache: no

- name: Add Docker GPG apt Key
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: false

- name: Run and enable docker
  service:
    name: docker
    state: started
    enabled: true


