---

- hosts: book
  sudo: yes
  tasks: 
  - name: install xbps docker
    when: ansible_distribution == "void"
    xbps: pkg={{item}} state=installed
    sudo: True
    with_items:
      - docker 
      - docker-compose
      - docker-machine
  
  - name: Ensure group "ihm" exists
    sudo: yes
    group:
     name: ihm
     state: present

  - name: Create symbolic link
    file:
     src: /etc/sv/{{ item.src }}
     dest: /etc/runit/runsvdir/default/{{ item.src }}
     owner: root
     group: root
     force: yes
     state: link
    with_items:
     - { src: 'docker'} 
  
  - name: Start sv docker, if running
    sudo: yes
    runit:
      name: docker
      state: started
