---
- hosts: void
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - { role: void, tags: ['void'] }
    - { role: cache, tags: ['cache'] }

- hosts: 127.0.0.1
  connection: local
  become: yes
  roles:
    - { role: debian, tags: ['debian'] }

- hosts: arch
  become: yes
  roles:
   - { role: arch, tags: ['arch'] }
 
